### ISSUE TITLE
object 'removal_index' not found

### ISSUE THREAD

**Issue by moomoofarm1** [theharmonylab/topics#1]
While running 
`dtm <- topicsDtm(data = dat1,
                 id_col = "id",
                 data_col = "text"
                 ,occ_rate = 0.0025
                 ,stopwords = stopwords`), 
the code works.

But while running
`dtm <- topicsDtm(data = dat1,
                 id_col = "id",
                 data_col = "text"
                 ,occ_rate = 0.0025
                 ,stopwords = stopwords
                 ,removal_rate_most = 5
                 ,removal_rate_least = 5
                 )`,
the code reports an error.

> Error in get_removal_terms(dtm, n, type, mode) : 
  object 'removal_index' not found

**Comment by LeonAckermann** [comment]
thanks for noticing! I added a default so this doesnt happen anymore
