### ISSUE TITLE
topicsTest does not support group_var without pred_var

### ISSUE THREAD

**Issue by moomoofarm1** [theharmonylab/topics#3]
By running
`if (unname(targs[num1]) == "Gender_T1"){
  preds <- preds %>%
    mutate(value = recode(value, "F" = "2", "M" = "1", .default = "0"))
}
test <- topicsTest(model = model,
                   data = dat1,
                   preds = preds,
                   group_var = targs[num1] # "Gender_T1"
                   ,test_method = "t-test"#'linear_regression' 
                   ,p_adjust_method = 'fdr'
                   ,seed = randSeed)
`
The error

> Error in topicsTest(model = model, data = dat1, preds = preds, group_var = targs[num1],  : 
  argument "pred_var" is missing, with no default

>

**Comment by LeonAckermann** [comment]
Check for pred_var added, default is not possible since its dependent on the user
